image: ubuntu:18.04

variables:
  http_proxy: http://10.7.211.16:911
  https_proxy: http://10.7.211.16:912

before_script:
  - whoami
  - export DEFAULT_COMPILER_FLAGS="-DCMAKE_CXX_COMPILER=clang++-10 -DCMAKE_C_COMPILER=clang-10"
  - export DEBUG_COMPILER_FLAGS="${DEFAULT_COMPILER_FLAGS} -DLATTICE_DEBUG=ON"
  - export DEFAULT_EXAMPLE_FLAGS="-DINTEL_LATTICE_LIBRARY=${CI_PROJECT_DIR}/build/libintel_lattice.a -DINTEL_LATTICE_HEADER=${CI_PROJECT_DIR}/intel-lattice/include"
  - export DEBUG_EXAMPLE_FLAGS="-DINTEL_LATTICE_LIBRARY=${CI_PROJECT_DIR}/build/libintel_lattice_debug.a -DINTEL_LATTICE_HEADER=${CI_PROJECT_DIR}/intel-lattice/include"
  - cmake --version

stages:
  - format
  - build
  - test
  - example
  - benchmark

format:
  stage: format
  only:
    refs:
      - merge_requests
      - master
  script:
    # Run formatting
    - pre-commit run --all-files

default_build:
  stage: build
  only:
    refs:
      - merge_requests
      - master
  script:
    - whoami
    - echo $HOME
    - echo "Testing from branch:"
    - echo $CI_COMMIT_REF_NAME
    - pwd

    # Build library
    - mkdir -p build
    - cd build
    - cmake .. ${DEFAULT_COMPILER_FLAGS}
    - make -j all
    # Build example
    - cd ../example
    - mkdir -p build
    - cd build
    - echo "DEFAULT_EXAMPLE_FLAGS"
    - echo ${DEFAULT_EXAMPLE_FLAGS}
    - cmake .. ${DEFAULT_COMPILER_FLAGS} ${DEFAULT_EXAMPLE_FLAGS}
    - make -j
  artifacts:
    paths:
        - build/
        - example/build
    expire_in: 1 day

debug_build:
  stage: build
  only:
    refs:
      - merge_requests
      - master
  script:
    - whoami
    - echo $HOME
    - echo "Testing from branch:"
    - echo $CI_COMMIT_REF_NAME
    - pwd

    # Build repo
    - mkdir -p build
    - cd build
    - cmake .. ${DEBUG_COMPILER_FLAGS}
    - make -j all
    # Build example
    - cd ../example
    - mkdir -p build
    - cd build
    - cmake .. ${DEBUG_COMPILER_FLAGS} ${DEBUG_EXAMPLE_FLAGS}
    - make -j
  artifacts:
    paths:
        - build/
        - example/build
    expire_in: 1 day

default_example:
  stage: example
  only:
    refs:
      - merge_requests
      - master
  script:
    - example/build/example
  artifacts:
    paths:
        - example/build
    expire_in: 1 day
  dependencies:
    - default_build

debug_example:
  stage: example
  only:
    refs:
      - merge_requests
      - master
  script:
    - example/build/example
  artifacts:
    paths:
        - example/build
    expire_in: 1 day
  dependencies:
    - debug_build

test:
  stage: test
  only:
    refs:
      - merge_requests
      - master
  script:
    - pwd
    - ls
    - build/test/unit-test
    - example/build/example
  dependencies:
    - default_build

debug_test:
  stage: test
  only:
    refs:
      - merge_requests
      - master
  script:
    - pwd
    - ls
    - build/test/unit-test
    - example/build/example
  dependencies:
    - debug_build

benchmark:
  stage: benchmark
  only:
    refs:
      - merge_requests
      - master
  script:
    - build/benchmark/bench_lattice --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}" --benchmark_out_format=csv
  dependencies:
  - default_build
  artifacts:
    paths:
      - "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 5 yr
