image: ubuntu:18.04

variables:
  http_proxy: http://10.7.211.16:911
  https_proxy: http://10.7.211.16:912
  no_proxy: docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16

stages:
  - format
  - build
  - test
  - benchmark

format:
  stage: format
  only:
    refs:
      - merge_requests
      - master
  script:
    # Run formatting
    - pre-commit run --all-files

build:
  stage: build
  only:
    refs:
      - merge_requests
      - master
  script:
    - whoami
    - echo $HOME
    - echo "Testing from branch:"
    - echo $CI_COMMIT_REF_NAME
    - pwd

    # Build repo
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER=clang++-10 -DCMAKE_C_COMPILER=clang-10 -DNTT_AVX512=OFF
    - make -j all

  artifacts:
    paths:
        - build/src/
        - build/test/
        - build/ext_easy_logging/
        - build/ext_gbenchmark/
        - build/
    expire_in: 1 day

build_avx512:
  stage: build
  only:
    refs:
      - merge_requests
      - master
  script:
    - whoami
    - echo $HOME
    - echo "Testing from branch:"
    - echo $CI_COMMIT_REF_NAME
    - pwd

    # Build repo
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER=clang++-10 -DCMAKE_C_COMPILER=clang-10  -DNTT_AVX512=ON
    - make -j all

  artifacts:
    paths:
        - build/src/
        - build/test/
        - build/ext_easy_logging/
        - build/ext_gbenchmark/
        - build/
    expire_in: 1 day

test:
  stage: test
  only:
    refs:
      - merge_requests
      - master
  script:
    - pwd
    - ls
    - build/test/unit-test

  dependencies:
    - build

test_avx512:
  stage: test
  only:
    refs:
      - merge_requests
      - master
  script:
    - pwd
    - ls
    - build/test/unit-test

  dependencies:
    - build_avx512

benchmark:
  stage: benchmark
  only:
    refs:
      - merge_requests
      - master

  script:
    - build/benchmark/bench_ntt --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}" --benchmark_out_format=csv

  dependencies:
  - build_avx512

  artifacts:
    paths:
      - "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 5 yr
